---
##############################################################################
## Play 1   Send lock session command to hosts.
##############################################################################
- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Lock Desktop
      win_command: RunDll32.exe user32.dll,LockWorkStation
      vars:
        ansible_become: yes
        ansible_become_method: runas
