---
- name: Bloquear la sesión de usuarios en equipos Windows
  hosts: all
  gather_facts: no
  tasks:
    - name: Bloquear la sesión del usuario actual en Windows
      community.windows.psexec: 
        hostname: WIN-4R2NH9V8HIU
        executable: C:\PSTools\psshutdown.exe
        arguments: -l
      ignore_errors: yes
