---
##############################################################################
## Play 1   Send lock session command to hosts.
##############################################################################
- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Lock Desktop
      win_shell: |
        rundll32.exe user32.dll, LockWorkStation
      ignore_errors: yes  # Evitar que el playbook falle si ya está bloqueado
