---
##############################################################################
## Play 1   Send lock session command to hosts.
##############################################################################
- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Lock Desktop
      win_shell: RunDll32.exe user32.dll,LockWorkStation
