---
##############################################################################
## Play 1   Send lock session command to hosts.
##############################################################################
- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Lock Desktop
      win_command: 'cmd.exe "Rundll32.exe user32.dll,LockWorkStation"'
