---
- name: Bloquear la sesión de usuarios en equipos Windows
  hosts: all
  gather_facts: no
  tasks:
    - name: Bloquear la sesión del usuario actual en Windows
      shell: |
        C:\PSTools\psshutdown.exe -l
      ignore_errors: yes
