---
##############################################################################
## Play 1   Search-only, return list of found updates (if any).
##############################################################################
- hosts: all
  become: true
  tasks:
    - name: Search-only, return list of found updates (if any).
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        state: searched
      register: list_of_found_updates

    - debug:
        var: list_of_found_updates

##############################################################################
### Play 2   Send info with telegram
##############################################################################
- hosts: localhost
  connection: local
  tasks:
    - name: Send telegram notification
      community.general.telegram:
        token: "{{ telegram_bot_token }}"
        api_args:
          chat_id: "{{ telegram_chat_id }}"
          parse_mode: "markdown"
          text: Host " {{ hostvars[inventory_hostname] }} " >> " {{ hostvars[inventory_hostname].list_of_found_updates.found_update_count }}.list_of_found_updates.found_update_count " updates found.
          disable_web_page_preview: true
          disable_notification: false
      with_items:
        -  "{{ groups[windows] }}"
      ignore_errors: yes


##############################################################################
#### Play 3    Install all security, critical, and rollup updates when install_updates is true
###############################################################################
- hosts: all
  become: true
  tasks:
    - name: Install all security, critical, and rollup updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: yes
      when:
          - install_updates == 'true'
