---
- name: Update Windows PC
  hosts: all
  become: true

  tasks:
    # Search, download and install Windows updates
    - name: Search, download and install Windows updates
      when: ansible.windows.win_ping == 'pong'
      win_updates:
         state: installed
