- name: Actualizar Windows
  hosts: windows
  tasks:
    - name: Instalar actualizaciones de Windows
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: yes
